@startuml
' ============================================================
' USE CASE DIAGRAM — SmartMart Koperasi Digital
' Lingkup : MODUL PENGGUNA (fokus aktor Anggota/Pengguna)
' Gaya    : satu aktor, satu system boundary, use case = elips
' ============================================================
left to right direction
!theme plain
skinparam defaultFontName Arial
skinparam shadowing false
skinparam packageStyle rectangle
skinparam usecase {
  BorderColor #777777
  FontSize 12
}
skinparam actor {
  BackgroundColor #FFFFFF
  BorderColor #222222
}

title **Use Case Diagram — Anggota (Modul Pengguna SmartMart)**

actor "Anggota\n(Pengguna)" as U

rectangle "Sistem SmartMart — Modul Pengguna" {
  usecase "Registrasi Akun"          as UC_REG      #DAE8FC
  usecase "Login Sistem"             as UC_LOGIN    #DAE8FC
  usecase "Dashboard Pengguna"       as UC_DASH     #DAE8FC

  usecase "Lihat Katalog\nProduk"    as UC_CATALOG  #D5E8D4
  usecase "Cari & Filter\nProduk"    as UC_SEARCH   #D5E8D4
  usecase "Kelola Wishlist"          as UC_WISH     #D5E8D4
  usecase "Checkout Pesanan"         as UC_CHECKOUT #D5E8D4

  usecase "Lihat & Lacak\nPesanan"   as UC_ORDERS   #FFE6CC
  usecase "Tulis Review\nProduk"     as UC_REVIEW   #FFE6CC
  usecase "Kelola Profil\n& Alamat"  as UC_PROFILE  #FFE6CC

  usecase "Lihat Saldo\n& Poin"      as UC_POINTS   #E1D5E7
  usecase "Tukar / Konversi\nPoin"   as UC_REDEEM   #E1D5E7
  usecase "Lihat Saldo\nSimpanan"    as UC_SAVING   #E1D5E7

  usecase "Validasi Role\n(RBAC)"    as UC_RBAC     #F8CECC
  usecase "Konfirmasi\nPembayaran"   as UC_PAY      #F8CECC
  usecase "Dapat Reward\nPoin"       as UC_EARN     #F8CECC
}

' ---------- Asosiasi Aktor ----------
U --> UC_REG
U --> UC_LOGIN
U --> UC_DASH
U --> UC_CATALOG
U --> UC_SEARCH
U --> UC_WISH
U --> UC_CHECKOUT
U --> UC_ORDERS
U --> UC_REVIEW
U --> UC_PROFILE
U --> UC_POINTS
U --> UC_REDEEM
U --> UC_SAVING

' ---------- «include» ----------
UC_LOGIN    ..> UC_RBAC : <<include>>
UC_CHECKOUT ..> UC_PAY  : <<include>>
UC_CHECKOUT ..> UC_EARN : <<include>>

caption Gambar 3.2 Use Case Diagram Anggota SmartMart
footer Use Case Diagram — SmartMart Koperasi Digital | Modul Pengguna & Dashboard | Tugas Akhir
@enduml
